-- Biblioteca de exercícios que vem com o app (E2.1).
-- Roda de novo sem duplicar: o slug é único e o insert ignora conflito.
-- Você pode criar os seus pelo app; estes ficam como base.

insert into exercicios (user_id, slug, nome, musculo_primario, musculos_secundarios, equipamento, tipo, nivel, instrucoes, erros_comuns) values
-- PEITO
('sistema','supino-reto-barra','Supino reto com barra','peito','{triceps,ombro_anterior}','barra','composto','iniciante','Desça a barra até o meio do peito com os cotovelos a cerca de 45° e empurre sem travar os ombros.','Descer a barra na altura do pescoço e soltar o quadril do banco.'),
('sistema','supino-inclinado-barra','Supino inclinado com barra','peito','{ombro_anterior,triceps}','barra','composto','iniciante','Banco a 30-45°; desça até a parte alta do peito.','Inclinar demais o banco, virando um desenvolvimento de ombro.'),
('sistema','supino-reto-halteres','Supino reto com halteres','peito','{triceps,ombro_anterior}','halter','composto','iniciante','Halteres na linha do peito, descida controlada até sentir alongar.','Bater os halteres no topo e perder a tensão.'),
('sistema','supino-inclinado-halteres','Supino inclinado com halteres','peito','{ombro_anterior,triceps}','halter','composto','iniciante','Banco a 30°; punhos alinhados com os cotovelos.','Arquear a lombar para empurrar mais peso.'),
('sistema','crucifixo-halteres','Crucifixo com halteres','peito','{ombro_anterior}','halter','isolado','iniciante','Cotovelos levemente flexionados e fixos; abra até o peito alongar.','Transformar em supino, dobrando e estendendo o cotovelo.'),
('sistema','crossover-cabo','Crossover na polia','peito','{ombro_anterior}','cabo','isolado','iniciante','Tronco levemente à frente, junte as mãos na linha do umbigo.','Usar carga alta e puxar com o corpo.'),
('sistema','voador-maquina','Voador (peck deck)','peito','{ombro_anterior}','maquina','isolado','iniciante','Costas apoiadas, movimento só de ombro, sem empurrar com os braços.','Abrir demais e forçar a cápsula do ombro.'),
('sistema','flexao-de-braco','Flexão de braço','peito','{triceps,abdomen,ombro_anterior}','peso_corporal','composto','iniciante','Corpo em prancha, desça até o peito quase tocar o chão.','Quadril caído ou cotovelos abertos a 90°.'),
('sistema','paralelas-peito','Paralelas (dips) para peito','peito','{triceps,ombro_anterior}','peso_corporal','composto','intermediario','Tronco inclinado à frente e desça até sentir o peito alongar.','Descer além da amplitude confortável do ombro.'),
('sistema','supino-maquina','Supino na máquina','peito','{triceps,ombro_anterior}','maquina','composto','iniciante','Ajuste o banco para as manoplas ficarem na linha do peito.','Assento alto demais, jogando a carga para o ombro.'),
-- COSTAS
('sistema','barra-fixa-pronada','Barra fixa pronada','dorsal','{biceps,trapezio,antebraco}','peso_corporal','composto','intermediario','Pegada pronada, puxe levando o peito para a barra e desça controlado.','Balançar o corpo e não estender os braços embaixo.'),
('sistema','barra-fixa-supinada','Barra fixa supinada','dorsal','{biceps,antebraco}','peso_corporal','composto','intermediario','Pegada supinada na largura dos ombros; cotovelos rentes ao corpo.','Encurtar a amplitude e puxar só metade.'),
('sistema','puxada-frente-polia','Puxada frente na polia','dorsal','{biceps,trapezio}','cabo','composto','iniciante','Puxe a barra até a clavícula, peito aberto, sem deitar o tronco.','Puxar atrás da nuca ou usar impulso de tronco.'),
('sistema','remada-curvada-barra','Remada curvada com barra','dorsal','{trapezio,lombar,biceps}','barra','composto','intermediario','Tronco a ~45°, coluna neutra, puxe a barra ao umbigo.','Arredondar a lombar e subir o tronco a cada repetição.'),
('sistema','remada-cavalinho','Remada cavalinho','dorsal','{trapezio,biceps}','barra','composto','iniciante','Peito apoiado ou tronco firme; puxe os cotovelos para trás.','Encolher os ombros em vez de puxar com as costas.'),
('sistema','remada-unilateral-halter','Remada unilateral com halter','dorsal','{trapezio,biceps}','halter','composto','iniciante','Apoie uma mão no banco, coluna neutra, puxe o halter à cintura.','Girar o tronco para levantar mais carga.'),
('sistema','remada-baixa-polia','Remada baixa na polia','dorsal','{biceps,trapezio}','cabo','composto','iniciante','Tronco fixo, puxe até o abdômen e controle a volta.','Balançar o tronco para frente e para trás.'),
('sistema','remada-maquina','Remada na máquina','dorsal','{biceps,trapezio}','maquina','composto','iniciante','Peito apoiado; puxe as manoplas até a linha das costelas.','Soltar o peito do apoio no fim da série.'),
('sistema','pullover-polia','Pullover na polia alta','dorsal','{peito,triceps}','cabo','isolado','intermediario','Braços quase estendidos, puxe a barra até as coxas só com o dorsal.','Dobrar o cotovelo e virar uma tríceps testa.'),
('sistema','levantamento-terra','Levantamento terra','isquiotibiais','{gluteos,lombar,dorsal,trapezio}','barra','composto','avancado','Barra rente à canela, coluna neutra, empurre o chão e estenda quadril e joelho juntos.','Arredondar a lombar e puxar com os braços.'),
('sistema','terra-romeno','Terra romeno','isquiotibiais','{gluteos,lombar}','barra','composto','intermediario','Joelhos levemente flexionados, empurre o quadril para trás sentindo o posterior.','Agachar em vez de flexionar o quadril.'),
('sistema','encolhimento-halteres','Encolhimento com halteres','trapezio','{ombro_posterior}','halter','isolado','iniciante','Suba os ombros para as orelhas e desça controlado.','Girar os ombros em círculo.'),
('sistema','face-pull','Face pull na polia','ombro_posterior','{trapezio}','cabo','isolado','iniciante','Puxe a corda até a altura do rosto, abrindo os cotovelos.','Usar carga alta e puxar com o tronco.'),
-- OMBROS
('sistema','desenvolvimento-militar-barra','Desenvolvimento militar com barra','ombro_lateral','{ombro_anterior,triceps,abdomen}','barra','composto','intermediario','Em pé, abdômen firme, empurre a barra acima da cabeça sem arquear a lombar.','Usar impulso de perna sem querer (isso é outro exercício).'),
('sistema','desenvolvimento-halteres','Desenvolvimento com halteres','ombro_lateral','{ombro_anterior,triceps}','halter','composto','iniciante','Cotovelos levemente à frente, empurre até quase estender.','Bater os halteres no alto e perder a tensão.'),
('sistema','desenvolvimento-arnold','Desenvolvimento Arnold','ombro_anterior','{ombro_lateral,triceps}','halter','composto','intermediario','Comece com as palmas para você e gire enquanto empurra.','Girar rápido demais e perder o controle.'),
('sistema','elevacao-lateral-halteres','Elevação lateral','ombro_lateral','{trapezio}','halter','isolado','iniciante','Suba até a linha dos ombros liderando com os cotovelos.','Balançar o corpo e subir acima do ombro com trapézio.'),
('sistema','elevacao-lateral-cabo','Elevação lateral na polia','ombro_lateral','{trapezio}','cabo','isolado','iniciante','Polia baixa cruzando na frente do corpo; suba até a linha do ombro.','Dobrar demais o cotovelo, encurtando o braço de alavanca.'),
('sistema','elevacao-frontal-halteres','Elevação frontal','ombro_anterior','{peito}','halter','isolado','iniciante','Suba o halter à frente até a altura dos olhos.','Usar a lombar para jogar o peso para cima.'),
('sistema','crucifixo-inverso-halteres','Crucifixo inverso','ombro_posterior','{trapezio}','halter','isolado','iniciante','Tronco inclinado, abra os braços na linha dos ombros.','Puxar com o dorsal em vez do ombro posterior.'),
('sistema','crucifixo-inverso-maquina','Crucifixo inverso na máquina','ombro_posterior','{trapezio}','maquina','isolado','iniciante','Peito apoiado, abra até a linha dos ombros e controle a volta.','Encolher o ombro durante o movimento.'),
-- BÍCEPS
('sistema','rosca-direta-barra','Rosca direta com barra','biceps','{antebraco}','barra','isolado','iniciante','Cotovelos fixos ao lado do corpo; suba sem balançar.','Jogar o tronco para trás para vencer a última repetição.'),
('sistema','rosca-alternada-halteres','Rosca alternada','biceps','{antebraco}','halter','isolado','iniciante','Alterne os braços, girando o punho para fora ao subir.','Encolher o ombro para ajudar.'),
('sistema','rosca-martelo','Rosca martelo','biceps','{antebraco}','halter','isolado','iniciante','Pegada neutra (polegar para cima) do início ao fim.','Balançar os halteres usando o quadril.'),
('sistema','rosca-scott','Rosca Scott','biceps','{antebraco}','barra','isolado','intermediario','Braços apoiados no banco inclinado; desça até quase estender.','Não descer o suficiente, perdendo a parte mais difícil.'),
('sistema','rosca-concentrada','Rosca concentrada','biceps','{antebraco}','halter','isolado','iniciante','Cotovelo apoiado na coxa, suba concentrando no bíceps.','Usar o ombro para levantar.'),
('sistema','rosca-polia-baixa','Rosca na polia baixa','biceps','{antebraco}','cabo','isolado','iniciante','Tensão contínua; controle a descida em 2 segundos.','Deixar o peso cair na volta.'),
-- TRÍCEPS
('sistema','triceps-testa-barra','Tríceps testa','triceps','{}','barra','isolado','intermediario','Cotovelos apontando para o teto; desça a barra até a testa.','Abrir os cotovelos e virar um supino fechado.'),
('sistema','triceps-polia-corda','Tríceps na polia com corda','triceps','{}','cabo','isolado','iniciante','Cotovelos junto ao corpo; abra a corda no fim do movimento.','Inclinar o tronco e empurrar com o peso do corpo.'),
('sistema','triceps-frances-halter','Tríceps francês','triceps','{}','halter','isolado','iniciante','Halter atrás da cabeça, cotovelos apontados para cima.','Abrir os cotovelos para os lados.'),
('sistema','triceps-coice-halter','Tríceps coice','triceps','{}','halter','isolado','iniciante','Braço paralelo ao chão; estenda só o antebraço.','Balançar o braço inteiro.'),
('sistema','mergulho-banco','Mergulho no banco','triceps','{peito,ombro_anterior}','peso_corporal','composto','iniciante','Mãos no banco atrás do corpo; desça até 90° no cotovelo.','Descer demais e sobrecarregar o ombro.'),
('sistema','supino-fechado-barra','Supino fechado','triceps','{peito,ombro_anterior}','barra','composto','intermediario','Pegada na largura dos ombros, cotovelos rentes ao tronco.','Pegada estreita demais, forçando o punho.'),
-- PERNAS: QUADRÍCEPS
('sistema','agachamento-livre-barra','Agachamento livre','quadriceps','{gluteos,isquiotibiais,lombar,abdomen}','barra','composto','avancado','Pés na largura dos ombros, desça até a coxa passar da paralela mantendo o peito aberto.','Joelho caindo para dentro e lombar arredondando no fundo.'),
('sistema','agachamento-frontal','Agachamento frontal','quadriceps','{gluteos,abdomen}','barra','composto','avancado','Barra apoiada nos ombros à frente, cotovelos altos, tronco vertical.','Deixar os cotovelos caírem e perder a barra.'),
('sistema','agachamento-hack','Agachamento hack','quadriceps','{gluteos}','maquina','composto','iniciante','Costas apoiadas, desça controlado até a paralela.','Descolar o quadril do apoio no fundo.'),
('sistema','leg-press','Leg press','quadriceps','{gluteos,isquiotibiais}','maquina','composto','iniciante','Pés na largura do quadril; desça até 90° sem soltar o lombar do apoio.','Descer demais, arredondando a lombar.'),
('sistema','cadeira-extensora','Cadeira extensora','quadriceps','{}','maquina','isolado','iniciante','Estenda até quase travar e segure meio segundo no topo.','Jogar a carga com impulso do tronco.'),
('sistema','afundo-halteres','Afundo com halteres','quadriceps','{gluteos,isquiotibiais}','halter','composto','iniciante','Passo à frente, desça o joelho de trás até perto do chão.','Joelho da frente passando muito da ponta do pé.'),
('sistema','passada-halteres','Passada (walking lunge)','quadriceps','{gluteos,isquiotibiais}','halter','composto','intermediario','Caminhe alternando as pernas, tronco ereto.','Passos curtos que jogam tudo no joelho.'),
('sistema','bulgaro-halteres','Agachamento búlgaro','quadriceps','{gluteos,isquiotibiais}','halter','composto','intermediario','Pé de trás no banco; desça na vertical sobre a perna da frente.','Apoiar o peso na perna de trás.'),
('sistema','agachamento-sumo','Agachamento sumô','adutores','{quadriceps,gluteos}','barra','composto','intermediario','Pés bem afastados e pontas para fora; desça entre as pernas.','Joelhos colapsando para dentro.'),
('sistema','agachamento-peso-corporal','Agachamento livre sem peso','quadriceps','{gluteos}','peso_corporal','composto','iniciante','Desça como se fosse sentar numa cadeira, peso no meio do pé.','Levantar os calcanhares do chão.'),
-- PERNAS: POSTERIOR E GLÚTEO
('sistema','mesa-flexora','Mesa flexora','isquiotibiais','{panturrilha}','maquina','isolado','iniciante','Quadril apoiado; flexione levando o calcanhar ao glúteo.','Levantar o quadril do apoio para puxar mais.'),
('sistema','cadeira-flexora','Cadeira flexora','isquiotibiais','{panturrilha}','maquina','isolado','iniciante','Costas apoiadas; flexione o joelho controlando a volta.','Amplitude curta e carga alta.'),
('sistema','stiff-halteres','Stiff com halteres','isquiotibiais','{gluteos,lombar}','halter','composto','intermediario','Pernas quase retas, desça os halteres rente às pernas com quadril para trás.','Curvar a coluna em vez de flexionar o quadril.'),
('sistema','elevacao-pelvica-barra','Elevação pélvica (hip thrust)','gluteos','{isquiotibiais}','barra','composto','intermediario','Costas no banco, suba o quadril até alinhar tronco e coxa e aperte o glúteo.','Hiperextender a lombar no topo.'),
('sistema','cadeira-abdutora','Cadeira abdutora','abdutores','{gluteos}','maquina','isolado','iniciante','Abra as pernas contra a resistência e volte devagar.','Jogar o tronco para trás para abrir mais.'),
('sistema','cadeira-adutora','Cadeira adutora','adutores','{}','maquina','isolado','iniciante','Feche as pernas de forma controlada, sem bater as placas.','Amplitude excessiva no alongamento.'),
('sistema','coice-gluteo-cabo','Coice de glúteo na polia','gluteos','{isquiotibiais}','cabo','isolado','iniciante','Empurre o pé para trás estendendo o quadril, tronco firme.','Arquear a lombar para ganhar amplitude.'),
-- PANTURRILHA
('sistema','panturrilha-em-pe','Panturrilha em pé','panturrilha','{}','maquina','isolado','iniciante','Suba na ponta dos pés até o limite e desça alongando.','Fazer repetições curtas e rápidas.'),
('sistema','panturrilha-sentado','Panturrilha sentado','panturrilha','{}','maquina','isolado','iniciante','Joelhos flexionados a 90°; amplitude completa.','Usar impulso para subir.'),
('sistema','panturrilha-halteres','Panturrilha com halteres','panturrilha','{}','halter','isolado','iniciante','Em pé, halteres nas mãos, suba na ponta dos pés um pé por vez ou os dois.','Perder o equilíbrio e encurtar o movimento.'),
-- ABDÔMEN E LOMBAR
('sistema','prancha-abdominal','Prancha','abdomen','{lombar,ombro_anterior}','peso_corporal','isolado','iniciante','Corpo alinhado, glúteo e abdômen contraídos; conte o tempo.','Quadril alto ou lombar afundada.'),
('sistema','abdominal-supra','Abdominal supra','abdomen','{}','peso_corporal','isolado','iniciante','Suba enrolando a coluna, sem puxar a cabeça com as mãos.','Puxar o pescoço e usar impulso.'),
('sistema','elevacao-pernas-suspenso','Elevação de pernas suspenso','abdomen','{antebraco}','peso_corporal','isolado','intermediario','Pendurado na barra, suba as pernas sem balançar.','Usar balanço em vez do abdômen.'),
('sistema','abdominal-canivete','Abdominal canivete','abdomen','{quadriceps}','peso_corporal','isolado','intermediario','Suba tronco e pernas ao mesmo tempo, tocando as mãos nos pés.','Prender a respiração e forçar o pescoço.'),
('sistema','prancha-lateral','Prancha lateral','abdomen','{lombar}','peso_corporal','isolado','iniciante','Apoio no antebraço, quadril alto e alinhado; conte o tempo.','Deixar o quadril cair para o chão.'),
('sistema','rodinha-abdominal','Rodinha abdominal','abdomen','{lombar,ombro_anterior}','peso_corporal','isolado','avancado','Role para frente mantendo a lombar neutra; volte com o abdômen.','Arquear a lombar ao estender.'),
('sistema','abdominal-polia-alta','Abdominal na polia alta','abdomen','{}','cabo','isolado','iniciante','De joelhos, enrole a coluna trazendo os cotovelos aos joelhos.','Flexionar o quadril em vez da coluna.'),
('sistema','hiperextensao-banco-romano','Hiperextensão no banco romano','lombar','{gluteos,isquiotibiais}','peso_corporal','isolado','iniciante','Desça flexionando o quadril e volte até alinhar o tronco.','Passar da linha do corpo, hiperextendendo a lombar.'),
('sistema','good-morning-barra','Good morning','isquiotibiais','{lombar,gluteos}','barra','composto','avancado','Barra nas costas, empurre o quadril para trás mantendo a coluna neutra.','Usar carga alta antes de dominar o movimento.'),
('sistema','rosca-punho-barra','Rosca de punho','antebraco','{}','barra','isolado','iniciante','Antebraços apoiados; flexione só os punhos.','Usar carga que force o cotovelo.')
on conflict (slug) do nothing;
